#
# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# [START django_app]
# [START gaestd_py_django_app_yaml]
runtime: python310
env: standard
# entrypoint: gunicorn -b :$PORT main:app


handlers:
- url: /.*
  script: auto

runtime_config:
  python_version: 3

env_variables:
  # This setting is used in settings.py to configure your ALLOWED_HOSTS
  APPENGINE_URL: singular-chain-382307.uc.r.appspot.com
  DJANGO_SETTINGS_MODULE: "mysite.settings"


# [END gaestd_py_django_app_yaml]
# [END django_app]
